version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: attrition_db
    environment:
      POSTGRES_USER: attrition_user
      POSTGRES_PASSWORD: attrition_pass
      POSTGRES_DB: attrition_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
